// storefront-mobile/src/components/checkout/RewardPointsRedeem.tsx
import { useCallback, useEffect, useRef, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { validateRewardPoints } from "../../lib/api";
import type { RewardPointsBalance } from "../../lib/types";
import { useApp } from "../../contexts/AppContext";
import { LabeledInput } from "../LabeledInput";
import { useRtl } from "../../lib/rtl";

type Props = {
  token: string;
  balance: RewardPointsBalance;
  orderTotal: number;
  pointsToRedeem: number;
  onChange: (points: number, redeemAmount: number, isValid: boolean) => void;
};

/** Checkout reward points redeem with API validation (Qwik parity). */
export function RewardPointsRedeem({
  token,
  balance,
  orderTotal,
  pointsToRedeem,
  onChange,
}: Props) {
  const { t, accent } = useApp();
  const { textAlign, writingDirection, row } = useRtl();
  const [input, setInput] = useState(
    pointsToRedeem > 0 ? String(pointsToRedeem) : "",
  );
  const [validating, setValidating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [redeemAmount, setRedeemAmount] = useState(0);
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  const maxPoints = Number(balance.max_redeem_points ?? 0);
  const available = Number(
    balance.available ?? balance.balance ?? balance.points ?? 0,
  );
  const title = balance.name || t("rewards.defaultName");

  const runValidation = useCallback(
    async (points: number) => {
      setValidating(true);
      setError(null);
      try {
        const { data } = await validateRewardPoints(token, {
          requested_points: points,
          order_total: orderTotal,
        });
        setRedeemAmount(Number(data.redeem_amount) || 0);
        if (!data.is_valid && data.message) {
          setError(data.message);
        }
        onChangeRef.current(
          data.requested_points,
          data.redeem_amount,
          data.is_valid,
        );
      } catch {
        setError(t("rewards.validateError"));
        setRedeemAmount(0);
        onChangeRef.current(0, 0, false);
      } finally {
        setValidating(false);
      }
    },
    [token, orderTotal, t],
  );

  useEffect(() => {
    const points = parseInt(input, 10) || 0;
    const timer = setTimeout(() => void runValidation(points), 280);
    return () => clearTimeout(timer);
  }, [input, orderTotal, runValidation]);

  if (balance.enabled === false || maxPoints <= 0) {
    return null;
  }

  return (
    <View style={styles.wrap}>
      <Text style={[styles.title, { textAlign, writingDirection }]}>{title}</Text>
      <Text style={[styles.hint, { textAlign, writingDirection }]}>
        {t("rewards.hint", { available })}
        {maxPoints > 0 ? t("rewards.hintMax", { max: maxPoints }) : null}.
      </Text>
      <LabeledInput
        label={t("rewards.pointsToRedeem")}
        value={input}
        onChangeText={(v) => setInput(v.replace(/\D/g, ""))}
        keyboardType="number-pad"
        placeholder="0"
        editable={!validating}
      />
      <View style={[styles.row, { flexDirection: row }]}>
        <Pressable
          style={[styles.btn, { borderColor: accent }]}
          disabled={validating}
          onPress={() => {
            setInput(String(maxPoints));
          }}
        >
          <Text style={styles.btnText}>{t("rewards.useMax")}</Text>
        </Pressable>
        {input ? (
          <Pressable
            style={styles.btn}
            disabled={validating}
            onPress={() => setInput("")}
          >
            <Text style={styles.btnText}>{t("rewards.clear")}</Text>
          </Pressable>
        ) : null}
      </View>
      {validating ? (
        <Text style={[styles.status, { textAlign }]}>{t("rewards.checking")}</Text>
      ) : null}
      {error ? (
        <Text style={[styles.error, { textAlign }]}>{error}</Text>
      ) : null}
      {redeemAmount > 0 && !error ? (
        <Text style={[styles.savings, { textAlign }]}>
          {t("rewards.discount")}{" "}
          <Text style={styles.savingsStrong}>
            {redeemAmount.toFixed(2)} EGP
          </Text>
        </Text>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { marginTop: 8, marginBottom: 8, gap: 6 },
  title: { fontWeight: "800", fontSize: 16, color: "#111" },
  hint: { color: "#666", lineHeight: 18 },
  row: { gap: 8, marginBottom: 4 },
  btn: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: "#fff",
  },
  btnText: { fontWeight: "700", color: "#222" },
  status: { color: "#666" },
  error: { color: "#B00020" },
  savings: { color: "#0B6E4F", fontWeight: "600" },
  savingsStrong: { fontWeight: "800" },
});

// storefront-qwik/src/components/checkout/reward-points-redeem.tsx
import { $, component$, useSignal, useVisibleTask$, type QRL } from "@builder.io/qwik";
import { validateRewardPoints } from "~/lib/api";
import { formatNumber, formatPrice } from "~/lib/format";
import { tStatic, useI18n } from "~/lib/i18n/context";
import type { RewardPointsBalance, StoreSettings } from "~/lib/types";

interface RewardPointsRedeemProps {
  token: string;
  balance: RewardPointsBalance;
  orderTotal: number;
  currency: StoreSettings["currency"];
  pointsToRedeem: number;
  onPointsChange$: QRL<(points: number, redeemAmount: number, isValid: boolean) => void>;
}

/** Checkout: redeem reward points against the order total. */
export const RewardPointsRedeem = component$<RewardPointsRedeemProps>((props) => {
  const { locale } = useI18n();
  const inputPoints = useSignal(props.pointsToRedeem > 0 ? String(props.pointsToRedeem) : "");
  const validating = useSignal(false);
  const error = useSignal<string | null>(null);
  const redeemAmount = useSignal(0);
  const maxPoints = props.balance.max_redeem_points ?? 0;

  const runValidation$ = $(async (points: number) => {
    validating.value = true;
    error.value = null;
    try {
      const { data } = await validateRewardPoints(props.token, {
        requested_points: points,
        order_total: props.orderTotal,
      });
      redeemAmount.value = data.redeem_amount;
      if (!data.is_valid && data.message) {
        error.value = data.message;
      }
      await props.onPointsChange$(data.requested_points, data.redeem_amount, data.is_valid);
    } catch {
      error.value = tStatic(locale, "rewards.validateError");
      redeemAmount.value = 0;
      await props.onPointsChange$(0, 0, false);
    } finally {
      validating.value = false;
    }
  });

  // Re-validate when cart total changes.
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track }) => {
    track(() => props.orderTotal);
    const points = parseInt(inputPoints.value, 10) || 0;
    void runValidation$(points);
  });

  const onInput$ = $(async (_: Event, el: HTMLInputElement) => {
    inputPoints.value = el.value.replace(/\D/g, "");
    const points = parseInt(inputPoints.value, 10) || 0;
    await runValidation$(points);
  });

  const useMax$ = $(async () => {
    inputPoints.value = String(maxPoints);
    await runValidation$(maxPoints);
  });

  const clear$ = $(async () => {
    inputPoints.value = "";
    await runValidation$(0);
  });

  if (!props.balance.enabled || maxPoints <= 0) {
    return null;
  }

  const title = props.balance.name || tStatic(locale, "rewards.defaultName");

  return (
    <div class="reward-points-redeem">
      <h3 class="reward-points-redeem__title">{title}</h3>
      <p class="footer-muted reward-points-redeem__hint">
        {tStatic(locale, "rewards.hint", {
          available: formatNumber(props.balance.available ?? 0, locale),
        })}
        {maxPoints > 0
          ? tStatic(locale, "rewards.hintMax", { max: formatNumber(maxPoints, locale) })
          : null}
        .
      </p>
      <div class="reward-points-redeem__row">
        <label class="sr-only" for="reward_points">
          {tStatic(locale, "rewards.pointsToRedeem")}
        </label>
        <input
          id="reward_points"
          type="text"
          inputMode="numeric"
          pattern="[0-9]*"
          placeholder="0"
          value={inputPoints.value}
          onInput$={onInput$}
          disabled={validating.value}
        />
        <button type="button" class="btn btn-secondary" onClick$={useMax$} disabled={validating.value}>
          {tStatic(locale, "rewards.useMax")}
        </button>
        {inputPoints.value ? (
          <button type="button" class="btn btn-secondary" onClick$={clear$} disabled={validating.value}>
            {tStatic(locale, "rewards.clear")}
          </button>
        ) : null}
      </div>
      {validating.value ? (
        <p class="footer-muted">{tStatic(locale, "rewards.checking")}</p>
      ) : null}
      {error.value ? <p class="alert alert-error">{error.value}</p> : null}
      {redeemAmount.value > 0 && !error.value ? (
        <p class="reward-points-redeem__savings">
          {tStatic(locale, "rewards.discount")}{" "}
          <strong>{formatPrice(redeemAmount.value, props.currency, locale)}</strong>
        </p>
      ) : null}
    </div>
  );
});
