// storefront-qwik/src/routes/[lang]/sell-to-us/index.tsx
import { $, component$, useSignal, useStore, useVisibleTask$ } from "@builder.io/qwik";
import {
  Link,
  routeLoader$,
  useLocation,
  type DocumentHead,
} from "@builder.io/qwik-city";
import { JsonLd } from "~/components/seo/json-ld";
import { LockIcon } from "~/components/icons";
import { SearchableSelect } from "~/components/forms/searchable-select";
import {
  ApiError,
  fetchSellToUsMeta,
  submitSellToUsRequest,
  verifySellToUsInvoice,
} from "~/lib/api";
import { isAuthenticated } from "~/lib/auth-actions";
import { useAuth } from "~/lib/auth-context";
import { isSupportedLocale } from "~/lib/i18n/config";
import { tStatic, useI18n } from "~/lib/i18n/context";
import { localePath } from "~/lib/i18n/paths";
import { toastError, toastSuccess } from "~/lib/notify";
import { publicSeoLinks } from "~/lib/seo-hreflang";
import { withStorefrontThemeHead } from "~/lib/storefront-head";
import type { SellToUsMeta, SellToUsType } from "~/lib/types";
import { useLangParam, useSiteSettings } from "~/routes/[lang]/layout";

export const useSellToUsPage = routeLoader$(async ({ params, redirect, resolveValue }) => {
  const locale = isSupportedLocale(params.lang) ? params.lang : "en";
  const settings = await resolveValue(useSiteSettings);
  if (!settings.sell_to_us?.enabled) {
    throw redirect(302, localePath(locale, "/"));
  }

  try {
    const { data } = await fetchSellToUsMeta(locale);
    return { meta: data, unavailable: false as const };
  } catch (e) {
    const status = e instanceof ApiError ? e.status : 0;
    if (status === 404) {
      throw redirect(302, localePath(locale, "/"));
    }
    return {
      meta: {
        enabled: true,
        types: [],
        cities: [],
        platforms: [
          { id: "ps5", label: "PS5" },
          { id: "ps4", label: "PS4" },
        ],
        device_models: [],
        storage_options: [],
        conditions: [],
        purchased_from_us: {
          invoice_required_when_yes: true,
          verify_required_when_yes: true,
        },
        max_photos: 6,
        max_photo_kb: 4096,
      } satisfies SellToUsMeta,
      unavailable: true as const,
    };
  }
});

/** Sell to us / trade-in quote request (logged-in customers). */
export default component$(() => {
  const page = useSellToUsPage();
  const { locale } = useI18n();
  const auth = useAuth();
  const loc = useLocation();
  const meta = page.value.meta;

  const type = useSignal<SellToUsType | "">("");
  const purchasedFromUs = useSignal(false);
  const invoiceVerified = useSignal(false);
  const verifiedTxnId = useSignal<number | null>(null);
  const verifying = useSignal(false);
  const submitting = useSignal(false);
  const photoFiles = useSignal<File[]>([]);

  const form = useStore({
    name: "",
    email: "",
    phone: "",
    city: "",
    notes: "",
    invoice_no: "",
    game_title: "",
    platform: "",
    condition: "",
    model: "",
    storage: "",
    account_note: "",
  });

  // Prefill from account once auth is ready.
  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(({ track }) => {
    track(() => auth.ready);
    track(() => auth.contact);
    if (!auth.ready || !auth.contact) return;
    if (!form.name) form.name = auth.contact.name || "";
    if (!form.email) form.email = auth.contact.email || "";
    if (!form.phone) form.phone = auth.contact.mobile || "";
    if (!form.city && auth.contact.city) form.city = auth.contact.city;
  });

  const selectType$ = $((id: SellToUsType) => {
    type.value = id;
  });

  const onPurchasedChange$ = $((yes: boolean) => {
    purchasedFromUs.value = yes;
    invoiceVerified.value = false;
    verifiedTxnId.value = null;
  });

  const onInvoiceInput$ = $((value: string) => {
    form.invoice_no = value;
    invoiceVerified.value = false;
    verifiedTxnId.value = null;
  });

  const verify$ = $(async () => {
    if (!auth.token) return;
    verifying.value = true;
    try {
      const { data } = await verifySellToUsInvoice(auth.token, form.invoice_no.trim());
      if (data.valid && data.order) {
        invoiceVerified.value = true;
        verifiedTxnId.value = data.order.id;
        await toastSuccess(tStatic(locale, "sellToUs.verified"));
      } else {
        await toastError(tStatic(locale, "sellToUs.verifyFailed"));
      }
    } catch (e) {
      await toastError(
        e instanceof ApiError ? e.message : tStatic(locale, "sellToUs.verifyFailed"),
      );
    } finally {
      verifying.value = false;
    }
  });

  const onPhotos$ = $((files: FileList | null) => {
    if (!files) {
      photoFiles.value = [];
      return;
    }
    photoFiles.value = Array.from(files).slice(0, meta.max_photos);
  });

  const submit$ = $(async () => {
    if (!auth.token || !type.value) return;
    if (purchasedFromUs.value && !invoiceVerified.value) {
      await toastError(tStatic(locale, "sellToUs.verifyRequired"));
      return;
    }

    submitting.value = true;
    try {
      const body = new FormData();
      body.append("type", type.value);
      body.append("name", form.name.trim());
      body.append("email", form.email.trim());
      body.append("phone", form.phone.trim());
      body.append("city", form.city.trim());
      body.append("notes", form.notes.trim());
      body.append("purchased_from_us", purchasedFromUs.value ? "1" : "0");
      if (purchasedFromUs.value) {
        body.append("invoice_no", form.invoice_no.trim());
        if (verifiedTxnId.value) {
          body.append("transaction_id", String(verifiedTxnId.value));
        }
      }

      const details: Record<string, string | number | null> = {};
      if (type.value === "account") {
        details.account_note = form.account_note.trim();
      } else if (type.value === "disc") {
        details.game_title = form.game_title.trim();
        details.platform = form.platform || null;
        details.condition = form.condition || null;
      } else if (type.value === "device") {
        details.model = form.model.trim();
        details.storage = form.storage.trim();
        details.condition = form.condition || null;
      }
      body.append("details", JSON.stringify(details));

      for (const file of photoFiles.value) {
        body.append("photos[]", file);
      }

      await submitSellToUsRequest(auth.token, body);
      await toastSuccess(tStatic(locale, "sellToUs.success"));
      form.notes = "";
      form.invoice_no = "";
      form.game_title = "";
      form.platform = "";
      form.condition = "";
      form.model = "";
      form.storage = "";
      form.account_note = "";
      purchasedFromUs.value = false;
      invoiceVerified.value = false;
      verifiedTxnId.value = null;
      photoFiles.value = [];
      type.value = "";
    } catch (e) {
      await toastError(
        e instanceof ApiError ? e.message : tStatic(locale, "sellToUs.submitFailed"),
      );
    } finally {
      submitting.value = false;
    }
  });

  const signedIn = isAuthenticated(auth);
  const loginNext = encodeURIComponent(loc.url.pathname);
  const howLd = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: tStatic(locale, "sellToUs.title"),
    description: tStatic(locale, "sellToUs.lead"),
    step: [
      {
        "@type": "HowToStep",
        name: tStatic(locale, "sellToUs.step1Title"),
        text: tStatic(locale, "sellToUs.step1Text"),
      },
      {
        "@type": "HowToStep",
        name: tStatic(locale, "sellToUs.step2Title"),
        text: tStatic(locale, "sellToUs.step2Text"),
      },
      {
        "@type": "HowToStep",
        name: tStatic(locale, "sellToUs.step3Title"),
        text: tStatic(locale, "sellToUs.step3Text"),
      },
    ],
  };

  // Full page gate until auth is known and the customer is signed in.
  if (!auth.ready || !signedIn) {
    return (
      <article class="content-page sell-to-us-page sell-to-us-page--gate">
        <nav class="breadcrumb" aria-label="Breadcrumb">
          <Link href={localePath(locale, "/")}>{tStatic(locale, "nav.home")}</Link>
          <span aria-hidden="true">/</span>
          <span>{tStatic(locale, "nav.sellToUs")}</span>
        </nav>

        <div class="sell-to-us-gate">
          {!auth.ready ? (
            <p class="footer-muted sell-to-us-gate__loading" aria-live="polite">
              …
            </p>
          ) : (
            <div class="sell-to-us-gate__card">
              <p class="sell-to-us-gate__badge">{tStatic(locale, "sellToUs.gateBadge")}</p>
              <div class="sell-to-us-gate__icon" aria-hidden="true">
                <LockIcon size={48} />
              </div>
              <h1 class="sell-to-us-gate__title">{tStatic(locale, "sellToUs.gateTitle")}</h1>
              <p class="sell-to-us-gate__lead">{tStatic(locale, "sellToUs.gateLead")}</p>
              <Link
                class="btn btn-primary sell-to-us-gate__cta"
                href={localePath(locale, `/login?next=${loginNext}`)}
              >
                {tStatic(locale, "sellToUs.loginCta")}
              </Link>
              <p class="sell-to-us-gate__register">
                {tStatic(locale, "sellToUs.gateRegisterBefore")}{" "}
                <Link href={localePath(locale, `/register?next=${loginNext}`)}>
                  {tStatic(locale, "sellToUs.gateRegisterLink")}
                </Link>{" "}
                {tStatic(locale, "sellToUs.gateRegisterAfter")}
              </p>
            </div>
          )}
        </div>
      </article>
    );
  }

  return (
    <article class="content-page sell-to-us-page">
      <JsonLd data={howLd} />
      <nav class="breadcrumb" aria-label="Breadcrumb">
        <Link href={localePath(locale, "/")}>{tStatic(locale, "nav.home")}</Link>
        <span aria-hidden="true">/</span>
        <span>{tStatic(locale, "nav.sellToUs")}</span>
      </nav>

      <p class="sell-to-us-badge">{tStatic(locale, "sellToUs.badge")}</p>
      <h1 class="content-title">{tStatic(locale, "sellToUs.title")}</h1>
      <p class="content-prose sell-to-us-lead">{tStatic(locale, "sellToUs.lead")}</p>

      <h2 class="sell-to-us-section-title">{tStatic(locale, "sellToUs.howTitle")}</h2>
      <ol class="sell-to-us-steps">
        <li>
          <strong>{tStatic(locale, "sellToUs.step1Title")}</strong>
          <span>{tStatic(locale, "sellToUs.step1Text")}</span>
        </li>
        <li>
          <strong>{tStatic(locale, "sellToUs.step2Title")}</strong>
          <span>{tStatic(locale, "sellToUs.step2Text")}</span>
        </li>
        <li>
          <strong>{tStatic(locale, "sellToUs.step3Title")}</strong>
          <span>{tStatic(locale, "sellToUs.step3Text")}</span>
        </li>
      </ol>

      {page.value.unavailable ? (
        <p class="footer-muted">{tStatic(locale, "sellToUs.loadFailed")}</p>
      ) : (
        <>
          <h2 class="sell-to-us-section-title">{tStatic(locale, "sellToUs.chooseType")}</h2>
          <div class="sell-to-us-types" role="group">
            {(
              [
                ["account", "sellToUs.typeAccount", "sellToUs.typeAccountHint"],
                ["disc", "sellToUs.typeDisc", "sellToUs.typeDiscHint"],
                ["device", "sellToUs.typeDevice", "sellToUs.typeDeviceHint"],
              ] as const
            ).map(([id, labelKey, hintKey]) => (
              <button
                key={id}
                type="button"
                class={`sell-to-us-type${type.value === id ? " is-active" : ""}`}
                onClick$={() => selectType$(id)}
              >
                <strong>{tStatic(locale, labelKey)}</strong>
                <span>{tStatic(locale, hintKey)}</span>
              </button>
            ))}
          </div>

          {type.value ? (
            <form
              class="sell-to-us-form"
              preventdefault:submit
              onSubmit$={submit$}
            >
              <h2 class="sell-to-us-section-title">{tStatic(locale, "sellToUs.formTitle")}</h2>

              <div class="sell-to-us-grid">
                <label>
                  <span>{tStatic(locale, "sellToUs.name")}</span>
                  <input
                    required
                    type="text"
                    value={form.name}
                    onInput$={(e) => {
                      form.name = (e.target as HTMLInputElement).value;
                    }}
                  />
                </label>
                <label>
                  <span>{tStatic(locale, "sellToUs.email")}</span>
                  <input
                    type="email"
                    value={form.email}
                    onInput$={(e) => {
                      form.email = (e.target as HTMLInputElement).value;
                    }}
                  />
                </label>
                <label>
                  <span>{tStatic(locale, "sellToUs.phone")}</span>
                  <input
                    type="tel"
                    value={form.phone}
                    onInput$={(e) => {
                      form.phone = (e.target as HTMLInputElement).value;
                    }}
                  />
                </label>
                <label>
                  <span>{tStatic(locale, "sellToUs.city")}</span>
                  <SearchableSelect
                    id="sell-city"
                    value={form.city}
                    placeholder={tStatic(locale, "sellToUs.selectCity")}
                    options={meta.cities.map((c) => ({
                      value: c.label,
                      label: c.label,
                    }))}
                    onChange$={(value) => {
                      form.city = value;
                    }}
                  />
                </label>
              </div>

              <fieldset class="sell-to-us-fieldset">
                <legend>{tStatic(locale, "sellToUs.purchasedFromUs")}</legend>
                <div class="sell-to-us-yesno">
                  <button
                    type="button"
                    class={!purchasedFromUs.value ? "is-active" : ""}
                    onClick$={() => onPurchasedChange$(false)}
                  >
                    {tStatic(locale, "sellToUs.no")}
                  </button>
                  <button
                    type="button"
                    class={purchasedFromUs.value ? "is-active" : ""}
                    onClick$={() => onPurchasedChange$(true)}
                  >
                    {tStatic(locale, "sellToUs.yes")}
                  </button>
                </div>
                {purchasedFromUs.value ? (
                  <div class="sell-to-us-verify">
                    <label>
                      <span>{tStatic(locale, "sellToUs.invoiceNo")}</span>
                      <input
                        required
                        type="text"
                        value={form.invoice_no}
                        onInput$={(e) =>
                          onInvoiceInput$((e.target as HTMLInputElement).value)
                        }
                      />
                    </label>
                    <button
                      type="button"
                      class="btn btn-secondary"
                      disabled={verifying.value || !form.invoice_no.trim()}
                      onClick$={verify$}
                    >
                      {tStatic(locale, "sellToUs.verify")}
                    </button>
                    {invoiceVerified.value ? (
                      <p class="sell-to-us-ok">{tStatic(locale, "sellToUs.verified")}</p>
                    ) : null}
                  </div>
                ) : null}
              </fieldset>

              {type.value === "account" ? (
                <label class="sell-to-us-block">
                  <span>{tStatic(locale, "sellToUs.accountNote")}</span>
                  <textarea
                    rows={3}
                    placeholder={tStatic(locale, "sellToUs.accountNotePlaceholder")}
                    value={form.account_note}
                    onInput$={(e) => {
                      form.account_note = (e.target as HTMLTextAreaElement).value;
                    }}
                  />
                </label>
              ) : null}

              {type.value === "disc" ? (
                <div class="sell-to-us-grid">
                  <label class="sell-to-us-span2">
                    <span>{tStatic(locale, "sellToUs.gameTitle")}</span>
                    <input
                      required
                      type="text"
                      value={form.game_title}
                      onInput$={(e) => {
                        form.game_title = (e.target as HTMLInputElement).value;
                      }}
                    />
                  </label>
                  <label>
                    <span>{tStatic(locale, "sellToUs.platform")}</span>
                    <SearchableSelect
                      id="sell-disc-platform"
                      value={form.platform}
                      placeholder="—"
                      options={meta.platforms.map((p) => ({
                        value: p.id,
                        label: p.label,
                      }))}
                      onChange$={(value) => {
                        form.platform = value;
                      }}
                    />
                  </label>
                  <label>
                    <span>{tStatic(locale, "sellToUs.condition")}</span>
                    <SearchableSelect
                      id="sell-disc-condition"
                      value={form.condition}
                      placeholder="—"
                      options={meta.conditions.map((c) => ({
                        value: c.id,
                        label: c.label,
                      }))}
                      onChange$={(value) => {
                        form.condition = value;
                      }}
                    />
                  </label>
                </div>
              ) : null}

              {type.value === "device" ? (
                <>
                  <div class="sell-to-us-grid">
                    <label>
                      <span>{tStatic(locale, "sellToUs.model")}</span>
                      <SearchableSelect
                        id="sell-device-model"
                        value={form.model}
                        placeholder="—"
                        required
                        options={meta.device_models.map((m) => ({
                          value: m.id,
                          label: m.label,
                        }))}
                        onChange$={(value) => {
                          form.model = value;
                        }}
                      />
                    </label>
                    <label>
                      <span>{tStatic(locale, "sellToUs.storage")}</span>
                      <SearchableSelect
                        id="sell-device-storage"
                        value={form.storage}
                        placeholder="—"
                        options={meta.storage_options.map((s) => ({
                          value: s.id,
                          label: s.label,
                        }))}
                        onChange$={(value) => {
                          form.storage = value;
                        }}
                      />
                    </label>
                    <label>
                      <span>{tStatic(locale, "sellToUs.condition")}</span>
                      <SearchableSelect
                        id="sell-device-condition"
                        value={form.condition}
                        placeholder="—"
                        required
                        options={meta.conditions.map((c) => ({
                          value: c.id,
                          label: c.label,
                        }))}
                        onChange$={(value) => {
                          form.condition = value;
                        }}
                      />
                    </label>
                  </div>
                  <label class="sell-to-us-block">
                    <span>{tStatic(locale, "sellToUs.photos")}</span>
                    <span class="footer-muted">
                      {tStatic(locale, "sellToUs.photosHint", {
                        max: String(meta.max_photos),
                        kb: String(meta.max_photo_kb),
                      })}
                    </span>
                    <input
                      type="file"
                      accept="image/*"
                      multiple
                      onChange$={(e) =>
                        onPhotos$((e.target as HTMLInputElement).files)
                      }
                    />
                  </label>
                </>
              ) : null}

              <label class="sell-to-us-block">
                <span>{tStatic(locale, "sellToUs.notes")}</span>
                <textarea
                  rows={3}
                  placeholder={tStatic(locale, "sellToUs.notesPlaceholder")}
                  value={form.notes}
                  onInput$={(e) => {
                    form.notes = (e.target as HTMLTextAreaElement).value;
                  }}
                />
              </label>

              <button
                type="submit"
                class="btn btn-primary"
                disabled={submitting.value}
              >
                {submitting.value
                  ? tStatic(locale, "sellToUs.submitting")
                  : tStatic(locale, "sellToUs.submit")}
              </button>
            </form>
          ) : null}
        </>
      )}
    </article>
  );
});

export const head: DocumentHead = ({ resolveValue, url }) => {
  const settings = resolveValue(useSiteSettings);
  const lang = resolveValue(useLangParam);
  const title = `${tStatic(lang, "sellToUs.title")} — ${settings.business_name}`;
  const description = tStatic(lang, "sellToUs.lead");

  return withStorefrontThemeHead(
    {
      title,
      meta: [
        { name: "description", content: description },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
        { property: "og:type", content: "website" },
        { property: "og:url", content: url.href },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: title },
        { name: "twitter:description", content: description },
      ],
      links: publicSeoLinks(url.origin, "/sell-to-us", lang),
    },
    settings,
  );
};

// storefront-mobile/app/sell-to-us.tsx
import { useEffect, useMemo, useState } from "react";
import {
  Image,
  Pressable,
  StyleSheet,
  Switch,
  Text,
  View,
} from "react-native";
import { Link, useRouter } from "expo-router";
import * as ImagePicker from "expo-image-picker";
import {
  ApiError,
  appendSellToUsPhoto,
  fetchSellToUsMeta,
  submitSellToUsRequest,
  verifySellToUsInvoice,
} from "../src/lib/api";
import { useApp } from "../src/contexts/AppContext";
import { toast } from "../src/lib/toast";
import { LabeledInput } from "../src/components/LabeledInput";
import { SelectField } from "../src/components/SelectField";
import {
  FormScrollView,
  LoadingBlock,
  PrimaryButton,
  Screen,
} from "../src/components/ui";
import type { SellToUsMeta, SellToUsType } from "../src/lib/types";

type PhotoAsset = { uri: string; fileName: string };

export default function SellToUsScreen() {
  const { t, settings, token, contact, accent, locale } = useApp();
  const router = useRouter();
  const enabled = settings?.sell_to_us?.enabled === true;

  const [meta, setMeta] = useState<SellToUsMeta | null>(null);
  const [loadingMeta, setLoadingMeta] = useState(true);
  const [type, setType] = useState<SellToUsType | "">("");
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [city, setCity] = useState("");
  const [notes, setNotes] = useState("");
  const [purchasedFromUs, setPurchasedFromUs] = useState(false);
  const [invoiceNo, setInvoiceNo] = useState("");
  const [verifiedTxnId, setVerifiedTxnId] = useState<number | null>(null);
  const [invoiceVerified, setInvoiceVerified] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [accountNote, setAccountNote] = useState("");
  const [gameTitle, setGameTitle] = useState("");
  const [platform, setPlatform] = useState("");
  const [condition, setCondition] = useState("");
  const [model, setModel] = useState("");
  const [storage, setStorage] = useState("");
  const [photos, setPhotos] = useState<PhotoAsset[]>([]);
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    if (!enabled) {
      setLoadingMeta(false);
      return;
    }
    setLoadingMeta(true);
    void fetchSellToUsMeta(locale)
      .then(({ data }) => setMeta(data))
      .catch(() => {
        setMeta(null);
        toast.error(t("sellToUs.loadFailed"));
      })
      .finally(() => setLoadingMeta(false));
  }, [enabled, locale, t]);

  useEffect(() => {
    if (!contact) return;
    if (!name) setName(contact.name || "");
    if (!email) setEmail(contact.email || "");
    if (!phone && contact.mobile) setPhone(contact.mobile);
  }, [contact, name, email, phone]);

  const maxPhotos = meta?.max_photos ?? 6;
  const maxPhotoKb = meta?.max_photo_kb ?? 4096;
  const requireVerify = Boolean(
    meta?.purchased_from_us?.verify_required_when_yes,
  );

  const typeOptions = useMemo(
    () =>
      (meta?.types || []).map((row) => ({
        value: row.id,
        label: row.label,
      })),
    [meta],
  );

  if (!enabled) {
    return (
      <Screen>
        <Text style={styles.muted}>{t("sellToUs.unavailable")}</Text>
        <PrimaryButton
          label={t("nav.home")}
          onPress={() => router.replace("/(tabs)")}
        />
      </Screen>
    );
  }

  if (!token) {
    return (
      <Screen padded={false}>
        <FormScrollView contentContainerStyle={{ padding: 16 }} bottomInset={64}>
          <Text style={[styles.badge, { color: accent }]}>
            {t("sellToUs.gateBadge")}
          </Text>
          <Text style={styles.title}>{t("sellToUs.gateTitle")}</Text>
          <Text style={styles.lead}>{t("sellToUs.gateLead")}</Text>
          <PrimaryButton
            label={t("sellToUs.loginCta")}
            onPress={() =>
              router.push({
                pathname: "/login",
                params: { next: "/sell-to-us" },
              })
            }
          />
          <Text style={styles.muted}>
            {t("sellToUs.gateRegisterBefore")}{" "}
            <Link
              href={{ pathname: "/register", params: { next: "/sell-to-us" } }}
              style={{ color: accent }}
            >
              {t("sellToUs.gateRegisterLink")}
            </Link>{" "}
            {t("sellToUs.gateRegisterAfter")}
          </Text>
        </FormScrollView>
      </Screen>
    );
  }

  if (loadingMeta) {
    return (
      <Screen>
        <LoadingBlock />
      </Screen>
    );
  }

  if (!meta) {
    return (
      <Screen>
        <Text style={styles.muted}>{t("sellToUs.loadFailed")}</Text>
      </Screen>
    );
  }

  return (
    <Screen padded={false} avoidKeyboard={false}>
      <FormScrollView contentContainerStyle={{ padding: 16 }} bottomInset={64}>
        <Text style={[styles.badge, { color: accent }]}>
          {t("sellToUs.badge")}
        </Text>
        <Text style={styles.title}>{t("sellToUs.title")}</Text>
        <Text style={styles.lead}>{t("sellToUs.lead")}</Text>

        <SelectField
          label={t("sellToUs.chooseType")}
          value={type}
          options={typeOptions}
          onChange={(value) => setType(value as SellToUsType | "")}
        />

        {!type ? null : (
          <>
            <LabeledInput
              label={t("sellToUs.name")}
              value={name}
              onChangeText={setName}
            />
            <LabeledInput
              label={t("sellToUs.email")}
              value={email}
              onChangeText={setEmail}
              autoCapitalize="none"
              keyboardType="email-address"
            />
            <LabeledInput
              label={t("sellToUs.phone")}
              value={phone}
              onChangeText={setPhone}
              keyboardType="phone-pad"
            />
            <SelectField
              label={t("sellToUs.city")}
              value={city}
              placeholder={t("sellToUs.selectCity")}
              options={(meta.cities || []).map((c) => ({
                value: c.id,
                label: c.label,
              }))}
              onChange={(value) => setCity(value)}
            />
            <LabeledInput
              label={t("sellToUs.notes")}
              value={notes}
              onChangeText={setNotes}
              multiline
              style={{ height: 90, textAlignVertical: "top" }}
              placeholder={t("sellToUs.notesPlaceholder")}
            />

            <View style={styles.switchRow}>
              <Text style={styles.switchLabel}>{t("sellToUs.purchasedFromUs")}</Text>
              <Switch
                value={purchasedFromUs}
                onValueChange={(yes) => {
                  setPurchasedFromUs(yes);
                  setInvoiceVerified(false);
                  setVerifiedTxnId(null);
                }}
              />
            </View>
            {purchasedFromUs ? (
              <View style={styles.verifyRow}>
                <View style={{ flex: 1 }}>
                  <LabeledInput
                    label={t("sellToUs.invoiceNo")}
                    value={invoiceNo}
                    onChangeText={(v) => {
                      setInvoiceNo(v);
                      setInvoiceVerified(false);
                      setVerifiedTxnId(null);
                    }}
                    autoCapitalize="none"
                  />
                </View>
                <PrimaryButton
                  label={verifying ? t("common.loading") : t("sellToUs.verify")}
                  disabled={verifying || !invoiceNo.trim()}
                  onPress={() => {
                    setVerifying(true);
                    void verifySellToUsInvoice(token, invoiceNo.trim())
                      .then(({ data }) => {
                        if (data.valid && data.order) {
                          setInvoiceVerified(true);
                          setVerifiedTxnId(data.order.id);
                          toast.success(t("sellToUs.verified"));
                        } else {
                          setInvoiceVerified(false);
                          setVerifiedTxnId(null);
                          toast.error(t("sellToUs.verifyFailed"));
                        }
                      })
                      .catch((e) =>
                        toast.error(
                          e instanceof ApiError
                            ? e.message
                            : t("sellToUs.verifyFailed"),
                        ),
                      )
                      .finally(() => setVerifying(false));
                  }}
                />
              </View>
            ) : null}
            {invoiceVerified ? (
              <Text style={[styles.ok, { color: accent }]}>
                {t("sellToUs.verified")}
              </Text>
            ) : null}

            {type === "account" ? (
              <LabeledInput
                label={t("sellToUs.accountNote")}
                value={accountNote}
                onChangeText={setAccountNote}
                multiline
                style={{ height: 90, textAlignVertical: "top" }}
                placeholder={t("sellToUs.accountNotePlaceholder")}
              />
            ) : null}

            {type === "disc" ? (
              <>
                <LabeledInput
                  label={t("sellToUs.gameTitle")}
                  value={gameTitle}
                  onChangeText={setGameTitle}
                />
                <SelectField
                  label={t("sellToUs.platform")}
                  value={platform}
                  options={(meta.platforms || []).map((p) => ({
                    value: p.id,
                    label: p.label,
                  }))}
                  onChange={setPlatform}
                />
                <SelectField
                  label={t("sellToUs.condition")}
                  value={condition}
                  options={(meta.conditions || []).map((c) => ({
                    value: c.id,
                    label: c.label,
                  }))}
                  onChange={setCondition}
                />
              </>
            ) : null}

            {type === "device" ? (
              <>
                <SelectField
                  label={t("sellToUs.model")}
                  value={model}
                  options={(meta.device_models || []).map((m) => ({
                    value: m.id,
                    label: m.label,
                  }))}
                  onChange={setModel}
                />
                <SelectField
                  label={t("sellToUs.storage")}
                  value={storage}
                  options={(meta.storage_options || []).map((s) => ({
                    value: s.id,
                    label: s.label,
                  }))}
                  onChange={setStorage}
                />
                <SelectField
                  label={t("sellToUs.condition")}
                  value={condition}
                  options={(meta.conditions || []).map((c) => ({
                    value: c.id,
                    label: c.label,
                  }))}
                  onChange={setCondition}
                />
                <Text style={styles.section}>{t("sellToUs.photos")}</Text>
                <Text style={styles.muted}>
                  {t("sellToUs.photosHint", {
                    max: maxPhotos,
                    kb: maxPhotoKb,
                  })}
                </Text>
                <View style={styles.photoRow}>
                  {photos.map((photo) => (
                    <Pressable
                      key={photo.uri}
                      onLongPress={() =>
                        setPhotos((prev) =>
                          prev.filter((p) => p.uri !== photo.uri),
                        )
                      }
                    >
                      <Image source={{ uri: photo.uri }} style={styles.photo} />
                    </Pressable>
                  ))}
                  {photos.length < maxPhotos ? (
                    <Pressable
                      style={styles.photoAdd}
                      onPress={() => {
                        void (async () => {
                          const permission =
                            await ImagePicker.requestMediaLibraryPermissionsAsync();
                          if (!permission.granted) {
                            toast.error(t("sellToUs.photoPermission"));
                            return;
                          }
                          const picked =
                            await ImagePicker.launchImageLibraryAsync({
                              mediaTypes: ["images"],
                              quality: 0.85,
                              allowsMultipleSelection: true,
                              selectionLimit: maxPhotos - photos.length,
                            });
                          if (picked.canceled) return;
                          const next = [...photos];
                          for (const asset of picked.assets) {
                            if (!asset.uri || next.length >= maxPhotos) break;
                            next.push({
                              uri: asset.uri,
                              fileName:
                                asset.fileName ||
                                `photo-${next.length + 1}.jpg`,
                            });
                          }
                          setPhotos(next);
                        })();
                      }}
                    >
                      <Text style={styles.photoAddText}>+</Text>
                    </Pressable>
                  ) : null}
                </View>
              </>
            ) : null}

            <PrimaryButton
              label={
                submitting ? t("sellToUs.submitting") : t("sellToUs.submit")
              }
              disabled={submitting}
              onPress={() => {
                if (!type || !name.trim() || !email.trim() || !phone.trim()) {
                  toast.error(t("sellToUs.submitFailed"));
                  return;
                }
                if (!city) {
                  toast.error(t("sellToUs.selectCity"));
                  return;
                }
                if (
                  purchasedFromUs &&
                  requireVerify &&
                  (!invoiceVerified || !verifiedTxnId)
                ) {
                  toast.error(t("sellToUs.verifyRequired"));
                  return;
                }
                if (type === "disc" && !gameTitle.trim()) {
                  toast.error(t("sellToUs.gameTitle"));
                  return;
                }
                if (type === "device" && (!model.trim() || !condition)) {
                  toast.error(t("sellToUs.submitFailed"));
                  return;
                }
                setSubmitting(true);
                void (async () => {
                  try {
                    const body = new FormData();
                    body.append("type", type);
                    body.append("name", name.trim());
                    body.append("email", email.trim());
                    body.append("phone", phone.trim());
                    body.append("city", city.trim());
                    body.append("notes", notes.trim());
                    body.append(
                      "purchased_from_us",
                      purchasedFromUs ? "1" : "0",
                    );
                    if (purchasedFromUs) {
                      body.append("invoice_no", invoiceNo.trim());
                      if (verifiedTxnId) {
                        body.append("transaction_id", String(verifiedTxnId));
                      }
                    }
                    const details: Record<string, string | null> = {};
                    if (type === "account") {
                      details.account_note = accountNote.trim();
                    } else if (type === "disc") {
                      details.game_title = gameTitle.trim();
                      details.platform = platform || null;
                      details.condition = condition || null;
                    } else if (type === "device") {
                      details.model = model.trim();
                      details.storage = storage.trim();
                      details.condition = condition || null;
                    }
                    body.append("details", JSON.stringify(details));
                    for (let i = 0; i < photos.length; i += 1) {
                      await appendSellToUsPhoto(body, photos[i].uri, i);
                    }
                    await submitSellToUsRequest(token, body);
                    toast.success(t("sellToUs.success"));
                    setType("");
                    setNotes("");
                    setInvoiceNo("");
                    setPurchasedFromUs(false);
                    setInvoiceVerified(false);
                    setVerifiedTxnId(null);
                    setAccountNote("");
                    setGameTitle("");
                    setPlatform("");
                    setCondition("");
                    setModel("");
                    setStorage("");
                    setPhotos([]);
                  } catch (e) {
                    toast.error(
                      e instanceof ApiError
                        ? e.message
                        : t("sellToUs.submitFailed"),
                    );
                  } finally {
                    setSubmitting(false);
                  }
                })();
              }}
            />
          </>
        )}
      </FormScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  badge: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  title: { fontSize: 22, fontWeight: "800", color: "#111", marginBottom: 8 },
  lead: { fontSize: 14, color: "#555", lineHeight: 20, marginBottom: 16 },
  muted: { color: "#777", marginBottom: 12, lineHeight: 20 },
  section: { fontWeight: "800", marginTop: 8, marginBottom: 6 },
  switchRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 10,
    gap: 12,
  },
  switchLabel: { flex: 1, fontWeight: "600", color: "#333" },
  verifyRow: { gap: 8, marginBottom: 8 },
  ok: { fontWeight: "700", marginBottom: 8 },
  photoRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 16 },
  photo: { width: 72, height: 72, borderRadius: 8 },
  photoAdd: {
    width: 72,
    height: 72,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  photoAddText: { fontSize: 28, color: "#666" },
});
