// storefront-qwik/src/routes/[lang]/account/payments/credits/index.tsx
import { $, component$, useSignal, useStore, useVisibleTask$ } from "@builder.io/qwik";
import { Link, type DocumentHead } from "@builder.io/qwik-city";
import { RewardPointsSummary } from "~/components/account/reward-points-summary";
import {
  ApiError,
  fetchAccountCoupons,
  fetchRewardPoints,
  fetchUsedAccountCoupons,
  saveAccountCoupon,
} from "~/lib/api";
import { useAuth } from "~/lib/auth-context";
import { formatPrice } from "~/lib/format";
import { tStatic, useI18n } from "~/lib/i18n/context";
import { localePath } from "~/lib/i18n/paths";
import { toastError, toastSuccess } from "~/lib/notify";
import { usePendingState } from "~/lib/pending-context";
import { withPendingFeedback } from "~/lib/with-pending";
import type { RewardPointsBalance, SavedCoupon, UsedCoupon } from "~/lib/types";
import { useLangParam, useSiteSettings } from "~/routes/[lang]/layout";

type CouponSub = "add" | "unused" | "used";

export default component$(() => {
  const auth = useAuth();
  const settings = useSiteSettings();
  const { locale } = useI18n();
  const pending = usePendingState();
  const couponSub = useSignal<CouponSub>("add");
  const code = useSignal("");
  const saving = useSignal(false);
  const creditsLoading = useSignal(false);
  const unused = useStore<{ items: SavedCoupon[] }>({ items: [] });
  const used = useStore<{ items: UsedCoupon[] }>({ items: [] });
  const rewardBalance = useSignal<RewardPointsBalance | null>(null);

  const couponTabs: { id: CouponSub; label: string }[] = [
    { id: "add", label: tStatic(locale, "account.couponAdd") },
    { id: "unused", label: tStatic(locale, "account.couponUnused") },
    { id: "used", label: tStatic(locale, "account.couponUsed") },
  ];

  const loadCredits$ = $(async () => {
    if (!auth.token) return;
    creditsLoading.value = true;
    try {
      const [rp, unusedRes, usedRes] = await Promise.all([
        fetchRewardPoints(auth.token).catch(() => ({
          data: null as RewardPointsBalance | null,
        })),
        fetchAccountCoupons(auth.token),
        fetchUsedAccountCoupons(auth.token),
      ]);
      rewardBalance.value = rp.data;
      unused.items = unusedRes.data || [];
      used.items = usedRes.data || [];
    } catch {
      await toastError(tStatic(locale, "account.loadOrdersFailed"));
    } finally {
      creditsLoading.value = false;
    }
  });

  // eslint-disable-next-line qwik/no-use-visible-task
  useVisibleTask$(async ({ track }) => {
    track(() => auth.token);
    if (!auth.token) return;
    await loadCredits$();
  });

  const saveCoupon$ = $(async () => {
    const trimmed = code.value.trim();
    if (!trimmed || !auth.token) return;
    await withPendingFeedback(pending, saving, async () => {
      try {
        await saveAccountCoupon(auth.token as string, trimmed);
        code.value = "";
        couponSub.value = "unused";
        await toastSuccess(tStatic(locale, "account.couponSaved"));
        await loadCredits$();
      } catch (e) {
        await toastError(
          e instanceof ApiError ? e.message : tStatic(locale, "account.saveFailed"),
        );
      }
    });
  });

  return (
    <div>
      <p class="footer-muted" style={{ marginBottom: "1rem" }}>
        <Link href={localePath(locale, "/account/payments")} class="link-accent">
          {tStatic(locale, "account.paymentsPayouts")}
        </Link>
      </p>
      <h1 class="page-title">{tStatic(locale, "account.creditsCoupons")}</h1>

      {rewardBalance.value?.enabled ? (
        <div style={{ marginBottom: "1.5rem" }}>
          <RewardPointsSummary
            balance={rewardBalance.value}
            currency={settings.value.currency}
          />
        </div>
      ) : null}

      <div class="account-hub-tabs" role="tablist">
        {couponTabs.map((tab) => (
          <button
            key={tab.id}
            type="button"
            class={couponSub.value === tab.id ? "account-hub-tab active" : "account-hub-tab"}
            onClick$={() => (couponSub.value = tab.id)}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {creditsLoading.value ? (
        <p class="footer-muted">{tStatic(locale, "common.loading")}</p>
      ) : null}

      {couponSub.value === "add" ? (
        <form class="account-form" preventdefault:submit onSubmit$={saveCoupon$}>
          <label for="wallet_code">{tStatic(locale, "account.couponCode")}</label>
          <input
            id="wallet_code"
            value={code.value}
            onInput$={(_, el) => (code.value = el.value)}
            autoCapitalize="characters"
          />
          <button type="submit" class="btn btn-primary" disabled={saving.value}>
            {saving.value
              ? tStatic(locale, "common.loading")
              : tStatic(locale, "account.couponSave")}
          </button>
        </form>
      ) : null}

      {couponSub.value === "unused" && unused.items.length === 0 && !creditsLoading.value ? (
        <p class="empty-state">{tStatic(locale, "account.couponEmptyUnused")}</p>
      ) : null}
      {couponSub.value === "unused"
        ? unused.items.map((item) => (
            <article key={item.id} class="account-card" style={{ marginBottom: "0.75rem" }}>
              <strong>{item.code}</strong>
              <span class="footer-muted">{item.label || item.name || ""}</span>
            </article>
          ))
        : null}

      {couponSub.value === "used" && used.items.length === 0 && !creditsLoading.value ? (
        <p class="empty-state">{tStatic(locale, "account.couponEmptyUsed")}</p>
      ) : null}
      {couponSub.value === "used"
        ? used.items.map((item) => (
            <article key={item.id} class="account-card" style={{ marginBottom: "0.75rem" }}>
              <strong>{item.code || "—"}</strong>
              <span class="footer-muted">
                {tStatic(locale, "account.couponUsedOn")} #{item.order_id}
                {item.discount_amount != null
                  ? ` · ${tStatic(locale, "account.couponSavedAmount")} ${formatPrice(item.discount_amount, settings.value.currency, locale)}`
                  : ""}
              </span>
              {item.order_id ? (
                <Link
                  href={localePath(locale, `/account/orders/${item.order_id}`)}
                  class="link-accent"
                >
                  {tStatic(locale, "account.view")}
                </Link>
              ) : null}
            </article>
          ))
        : null}
    </div>
  );
});

export const head: DocumentHead = ({ resolveValue }) => {
  const lang = resolveValue(useLangParam);
  return {
    title: tStatic(lang, "account.creditsCoupons"),
    meta: [{ name: "robots", content: "noindex, nofollow" }],
  };
};

// storefront-mobile/app/account/payments/credits.tsx
import { useCallback, useEffect, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Redirect, useRouter } from "expo-router";
import {
  fetchAccountCoupons,
  fetchRewardPoints,
  fetchUsedAccountCoupons,
  saveAccountCoupon,
} from "../../../src/lib/api";
import type {
  RewardPointsBalance,
  SavedCoupon,
  UsedCoupon,
} from "../../../src/lib/types";
import { useApp } from "../../../src/contexts/AppContext";
import { UnderlineTabs } from "../../../src/components/account/UnderlineTabs";
import { LabeledInput } from "../../../src/components/LabeledInput";
import {
  ErrorBlock,
  LoadingBlock,
  PrimaryButton,
  Screen,
} from "../../../src/components/ui";
import { toast } from "../../../src/lib/toast";

type CouponSub = "add" | "unused" | "used";

export default function CreditsCouponsScreen() {
  const { token, t, settings } = useApp();
  const router = useRouter();
  const [couponSub, setCouponSub] = useState<CouponSub>("add");
  const [code, setCode] = useState("");
  const [saving, setSaving] = useState(false);
  const [rewards, setRewards] = useState<RewardPointsBalance | null>(null);
  const [unused, setUnused] = useState<SavedCoupon[]>([]);
  const [used, setUsed] = useState<UsedCoupon[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    if (!token) return;
    setLoading(true);
    try {
      const [rp, unusedRes, usedRes] = await Promise.all([
        fetchRewardPoints(token).catch(() => ({ data: null })),
        fetchAccountCoupons(token),
        fetchUsedAccountCoupons(token),
      ]);
      setRewards(rp.data);
      setUnused(unusedRes.data || []);
      setUsed(usedRes.data || []);
      setError(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : t("common.error"));
    } finally {
      setLoading(false);
    }
  }, [token, t]);

  useEffect(() => {
    void load();
  }, [load]);

  if (!token) {
    return <Redirect href="/login" />;
  }

  return (
    <Screen padded={false}>
      <ScrollView contentContainerStyle={styles.pad}>
        {loading ? <LoadingBlock /> : null}
        {error ? <ErrorBlock message={error} onRetry={() => void load()} /> : null}

        {rewards?.enabled !== false ? (
          <View style={styles.card}>
            <Text style={styles.title}>{t("account.rewardPoints")}</Text>
            <Text style={styles.meta}>
              {Number(
                rewards?.available ?? rewards?.balance ?? rewards?.points ?? 0,
              ).toFixed(1)}
              {settings?.currency?.code ? ` · ${settings.currency.code}` : ""}
            </Text>
          </View>
        ) : null}

        <UnderlineTabs
          value={couponSub}
          onChange={setCouponSub}
          items={[
            { id: "add", label: t("account.couponAdd") },
            { id: "unused", label: t("account.couponUnused") },
            { id: "used", label: t("account.couponUsed") },
          ]}
        />

        {couponSub === "add" ? (
          <View style={styles.form}>
            <LabeledInput
              label={t("account.couponCode")}
              value={code}
              onChangeText={setCode}
              autoCapitalize="characters"
            />
            <PrimaryButton
              label={saving ? t("common.loading") : t("account.couponSave")}
              disabled={saving}
              onPress={() => {
                const trimmed = code.trim();
                if (!trimmed) return;
                setSaving(true);
                void saveAccountCoupon(token, trimmed)
                  .then(() => {
                    toast.success(t("account.couponSaved"));
                    setCode("");
                    setCouponSub("unused");
                    void load();
                  })
                  .catch((e) =>
                    toast.error(
                      e instanceof Error ? e.message : t("common.error"),
                    ),
                  )
                  .finally(() => setSaving(false));
              }}
            />
          </View>
        ) : null}

        {couponSub === "unused"
          ? unused.map((item) => (
              <View key={item.id} style={styles.card}>
                <Text style={styles.title}>{item.code}</Text>
                <Text style={styles.meta}>{item.label || item.name || ""}</Text>
              </View>
            ))
          : null}
        {couponSub === "unused" && unused.length === 0 && !loading ? (
          <Text style={styles.empty}>{t("account.couponEmptyUnused")}</Text>
        ) : null}

        {couponSub === "used"
          ? used.map((item) => (
              <Pressable
                key={item.id}
                style={styles.card}
                onPress={() => {
                  if (item.order_id) {
                    router.push(`/account/orders/${item.order_id}`);
                  }
                }}
              >
                <Text style={styles.title}>{item.code || "—"}</Text>
                <Text style={styles.meta}>
                  #{item.order_id}
                  {item.discount_amount != null
                    ? ` · ${t("account.couponSavedAmount")} ${Number(item.discount_amount).toFixed(2)}`
                    : ""}
                </Text>
              </Pressable>
            ))
          : null}
        {couponSub === "used" && used.length === 0 && !loading ? (
          <Text style={styles.empty}>{t("account.couponEmptyUsed")}</Text>
        ) : null}
      </ScrollView>
    </Screen>
  );
}

const styles = StyleSheet.create({
  pad: { paddingBottom: 48 },
  form: { padding: 16 },
  card: {
    backgroundColor: "#fff",
    padding: 14,
    borderRadius: 10,
    marginHorizontal: 16,
    marginTop: 12,
  },
  title: { fontWeight: "800", marginBottom: 4 },
  meta: { color: "#555" },
  empty: { textAlign: "center", color: "#666", marginTop: 24 },
});
