// storefront-mobile/src/components/catalog/StarRating.tsx
import { StyleSheet, Text, View } from "react-native";
import { useApp } from "../../contexts/AppContext";
import { useRtl } from "../../lib/rtl";

type Props = {
  average: number;
  count?: number;
  size?: "sm" | "md";
  showCount?: boolean;
  showAverage?: boolean;
};

/** Read-only star display for card / PDP aggregates. */
export function StarRating({
  average,
  count = 0,
  size = "sm",
  showCount,
  showAverage = true,
}: Props) {
  const { t } = useApp();
  const { row, textAlign } = useRtl();
  const avg = Math.max(0, Math.min(5, Number(average) || 0));
  const rounded = Math.round(avg * 2) / 2;
  const starSize = size === "md" ? 16 : 13;
  const shouldShowCount = showCount ?? count > 0;

  return (
    <View
      style={[styles.wrap, { flexDirection: row }]}
      accessibilityRole="text"
      accessibilityLabel={t("reviews.averageTitle", {
        average: avg.toFixed(1),
        count,
      })}
    >
      <View style={[styles.stars, { flexDirection: row }]}>
        {[1, 2, 3, 4, 5].map((star) => {
          const filled = rounded >= star;
          const half = !filled && rounded >= star - 0.5;
          return (
            <Text
              key={star}
              style={[
                styles.star,
                { fontSize: starSize },
                filled || half ? styles.starOn : styles.starOff,
              ]}
            >
              {half ? "⯨" : "★"}
            </Text>
          );
        })}
      </View>
      {shouldShowCount ? (
        <Text style={[styles.meta, { textAlign, fontSize: starSize }]}>
          {showAverage ? `${avg.toFixed(1)} ` : ""}
          ({t("reviews.countLabel", { count })})
        </Text>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: { alignItems: "center", gap: 6, flexWrap: "wrap" },
  stars: { alignItems: "center", gap: 1 },
  star: { lineHeight: 18 },
  starOn: { color: "#F5A623" },
  starOff: { color: "rgba(120,120,120,0.45)" },
  meta: { color: "#666", fontWeight: "600" },
});

// storefront-qwik/src/components/catalog/star-rating.tsx
import { component$ } from "@builder.io/qwik";
import { tStatic, useI18n } from "~/lib/i18n/context";

interface StarRatingProps {
  average: number;
  count?: number;
  size?: "sm" | "md";
  showCount?: boolean;
}

/** Read-only star display for aggregates (cards + PDP summary). */
export const StarRating = component$<StarRatingProps>((props) => {
  const { locale } = useI18n();
  const average = Math.max(0, Math.min(5, Number(props.average) || 0));
  const count = props.count ?? 0;
  const size = props.size ?? "sm";
  const showCount = props.showCount ?? count > 0;
  const rounded = Math.round(average * 2) / 2;

  return (
    <span
      class={`star-rating star-rating--${size}`}
      title={tStatic(locale, "reviews.averageTitle", {
        average: average.toFixed(1),
        count: String(count),
      })}
    >
      <span class="star-rating__stars" aria-hidden="true">
        {[1, 2, 3, 4, 5].map((star) => {
          const filled = rounded >= star;
          const half = !filled && rounded >= star - 0.5;
          return (
            <span
              key={star}
              class={`star-rating__star${filled ? " star-rating__star--full" : ""}${half ? " star-rating__star--half" : ""}`}
            >
              ★
            </span>
          );
        })}
      </span>
      {showCount ? (
        <span class="star-rating__meta">
          <span class="star-rating__avg">{average.toFixed(1)}</span>
          <span class="star-rating__count">
            ({tStatic(locale, "reviews.countLabel", { count: String(count) })})
          </span>
        </span>
      ) : null}
      <span class="sr-only">
        {tStatic(locale, "reviews.averageTitle", {
          average: average.toFixed(1),
          count: String(count),
        })}
      </span>
    </span>
  );
});
