// storefront-mobile/app/custom-bundle.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  FlatList,
  Image,
  Modal,
  Pressable,
  StyleSheet,
  Text,
  TextInput,
  View,
} from "react-native";
import FontAwesome from "@expo/vector-icons/FontAwesome";
import { useRouter } from "expo-router";
import type { KeyboardAwareScrollViewRef } from "react-native-keyboard-controller";
import {
  ApiError,
  fetchCustomBundleMeta,
  fetchCustomBundleProducts,
  fetchProduct,
} from "../src/lib/api";
import { useApp } from "../src/contexts/AppContext";
import { useCart } from "../src/contexts/CartContext";
import { toast } from "../src/lib/toast";
import {
  FormScrollView,
  LoadingBlock,
  PrimaryButton,
  Screen,
} from "../src/components/ui";
import type {
  CartItem,
  CustomBundleMeta,
  ProductSummary,
} from "../src/lib/types";

type BundleLine = {
  key: string;
  productId: number;
  variationId: number;
  slug?: string | null;
  name: string;
  variationName: string;
  price: number;
  quantity: number;
  imageUrl?: string | null;
};

type VariationOption = {
  id: number;
  name: string;
  price: number;
};

export default function CustomBundleScreen() {
  const { t, settings, locale, accent } = useApp();
  const { addItem } = useCart();
  const router = useRouter();
  const enabled = settings?.custom_bundle?.enabled === true;

  const [meta, setMeta] = useState<CustomBundleMeta | null>(null);
  const [platform, setPlatform] = useState("");
  const [tab, setTab] = useState("all");
  const [tabs, setTabs] = useState<Array<{ id: string; label: string }>>([
    { id: "all", label: t("customBundle.tabAll") },
  ]);
  const [query, setQuery] = useState("");
  const [products, setProducts] = useState<ProductSummary[]>([]);
  const [loading, setLoading] = useState(false);
  const [selection, setSelection] = useState<BundleLine[]>([]);
  const [picker, setPicker] = useState<{
    productId: number;
    name: string;
    slug?: string | null;
    imageUrl?: string | null;
    options: VariationOption[];
  } | null>(null);
  const [submitting, setSubmitting] = useState(false);
  const scrollRef = useRef<KeyboardAwareScrollViewRef>(null);
  const trayOffsetY = useRef(0);

  const minItems = meta?.min_items ?? settings?.custom_bundle?.min_items ?? 2;
  const maxItems = meta?.max_items ?? settings?.custom_bundle?.max_items ?? 15;
  const selectionCount = selection.reduce((sum, row) => sum + row.quantity, 0);
  const selectionTotal = selection.reduce(
    (sum, row) => sum + row.price * row.quantity,
    0,
  );

  useEffect(() => {
    if (!enabled) return;
    void fetchCustomBundleMeta(locale)
      .then(({ data }) => {
        setMeta(data);
        if (data.platforms?.length && !platform) {
          // leave platform empty until user picks
        }
      })
      .catch(() => setMeta(null));
  }, [enabled, locale]);

  useEffect(() => {
    if (!platform) {
      setTabs([{ id: "all", label: t("customBundle.tabAll") }]);
      setTab("all");
      setProducts([]);
      return;
    }
    void fetchCustomBundleMeta(locale, platform)
      .then(({ data }) => {
        const nextTabs =
          data.tabs?.length > 0
            ? data.tabs
            : [{ id: "all", label: t("customBundle.tabAll") }];
        setTabs(nextTabs);
        if (!nextTabs.some((row) => row.id === tab)) {
          setTab("all");
        }
      })
      .catch(() => {
        setTabs([{ id: "all", label: t("customBundle.tabAll") }]);
        setTab("all");
      });
  }, [platform, locale, t]);

  const loadProducts = useCallback(() => {
    if (!platform) {
      setProducts([]);
      return;
    }
    setLoading(true);
    void fetchCustomBundleProducts(
      {
        platform,
        tab,
        q: query.trim() || undefined,
        per_page: 40,
      },
      locale,
    )
      .then(({ data }) => setProducts(data || []))
      .catch(() => {
        setProducts([]);
        toast.error(t("customBundle.loadFailed"));
      })
      .finally(() => setLoading(false));
  }, [platform, tab, query, locale, t]);

  useEffect(() => {
    loadProducts();
  }, [loadProducts]);

  const addLine = (line: BundleLine) => {
    const count = selection.reduce((sum, row) => sum + row.quantity, 0);
    if (count >= maxItems) {
      toast.error(t("customBundle.maxReached", { max: maxItems }));
      return;
    }
    setSelection((prev) => {
      const existing = prev.find((row) => row.key === line.key);
      if (existing) {
        if (count + 1 > maxItems) {
          toast.error(t("customBundle.maxReached", { max: maxItems }));
          return prev;
        }
        return prev.map((row) =>
          row.key === line.key
            ? { ...row, quantity: row.quantity + 1 }
            : row,
        );
      }
      return [...prev, line];
    });
  };

  const tryAddProduct = async (product: ProductSummary) => {
    if (!product.variation_id || !product.in_stock) return;
    try {
      if (product.has_options) {
        const { data: detail } = await fetchProduct(String(product.id), locale);
        const options = (detail.variations || [])
          .filter((v) => v.in_stock)
          .map((v) => ({ id: v.id, name: v.name, price: v.price }));
        if (options.length === 0) {
          toast.error(t("customBundle.unavailable"));
          return;
        }
        if (options.length === 1) {
          const only = options[0];
          addLine({
            key: `v:${only.id}`,
            productId: product.id,
            variationId: only.id,
            slug: product.slug,
            name: product.name,
            variationName: only.name,
            price: only.price,
            quantity: 1,
            imageUrl: product.image_url,
          });
          return;
        }
        setPicker({
          productId: product.id,
          name: product.name,
          slug: product.slug,
          imageUrl: product.image_url,
          options,
        });
        return;
      }
      addLine({
        key: `v:${product.variation_id}`,
        productId: product.id,
        variationId: product.variation_id,
        slug: product.slug,
        name: product.name,
        variationName: product.variation_name || "",
        price: Number(product.price ?? 0),
        quantity: 1,
        imageUrl: product.image_url,
      });
    } catch (e) {
      toast.error(
        e instanceof Error ? e.message : t("customBundle.loadFailed"),
      );
    }
  };

  const changeQty = (key: string, delta: number) => {
    setSelection((prev) => {
      const next: BundleLine[] = [];
      let total = 0;
      for (const row of prev) {
        if (row.key !== key) {
          total += row.quantity;
          next.push(row);
          continue;
        }
        const qty = row.quantity + delta;
        if (qty <= 0) continue;
        if (delta > 0 && total + qty > maxItems) continue;
        total += qty;
        next.push({ ...row, quantity: qty });
      }
      return next;
    });
  };

  const isInBundle = (product: ProductSummary) =>
    selection.some(
      (row) =>
        row.productId === product.id ||
        (product.variation_id != null && row.key === `v:${product.variation_id}`),
    );

  const removeOneOfProduct = (
    productId: number,
    variationId: number | null,
  ) => {
    setSelection((prev) => {
      const preferredKey = variationId ? `v:${variationId}` : null;
      const match =
        (preferredKey
          ? prev.find((row) => row.key === preferredKey)
          : undefined) || prev.find((row) => row.productId === productId);
      if (!match) return prev;
      if (match.quantity <= 1) {
        return prev.filter((row) => row.key !== match.key);
      }
      return prev.map((row) =>
        row.key === match.key
          ? { ...row, quantity: row.quantity - 1 }
          : row,
      );
    });
  };

  const scrollToBundle = () => {
    scrollRef.current?.scrollTo({ y: Math.max(0, trayOffsetY.current - 12), animated: true });
  };

  const submitBundle = async () => {
    if (selectionCount < minItems) {
      toast.error(t("customBundle.minRequired", { min: minItems }));
      return;
    }
    if (selectionCount > maxItems) {
      toast.error(t("customBundle.maxReached", { max: maxItems }));
      return;
    }
    setSubmitting(true);
    try {
      for (const row of selection) {
        const item: CartItem = {
          productId: row.productId,
          variationId: row.variationId,
          slug: row.slug || undefined,
          name: row.name,
          imageUrl: row.imageUrl,
          unitPrice: row.price,
          quantity: row.quantity,
        };
        await addItem(item);
      }
      toast.success(t("customBundle.addedToCart"));
      setSelection([]);
      router.push("/checkout");
    } catch (e) {
      toast.error(
        e instanceof ApiError
          ? e.message
          : t("customBundle.submitFailed"),
      );
    } finally {
      setSubmitting(false);
    }
  };

  const platforms = useMemo(() => meta?.platforms ?? [], [meta]);

  if (!enabled) {
    return (
      <Screen>
        <Text style={styles.muted}>{t("customBundle.unavailable")}</Text>
        <PrimaryButton
          label={t("nav.home")}
          onPress={() => router.replace("/(tabs)")}
        />
      </Screen>
    );
  }

  return (
    <Screen padded={false}>
      <FormScrollView
        ref={scrollRef}
        contentContainerStyle={{ padding: 16 }}
        bottomInset={120}
      >
        <Text style={[styles.badge, { color: accent }]}>
          {t("customBundle.badge")}
        </Text>
        <Text style={styles.title}>{t("customBundle.title")}</Text>
        <Text style={styles.lead}>{t("customBundle.lead")}</Text>

        <Text style={styles.section}>{t("customBundle.choosePlatform")}</Text>
        <View style={styles.chipRow}>
          {platforms.map((p) => {
            const active = platform === p.id;
            return (
              <Pressable
                key={p.id}
                style={[styles.chip, active && { backgroundColor: accent }]}
                onPress={() => setPlatform(p.id)}
              >
                <Text style={[styles.chipText, active && styles.chipTextActive]}>
                  {p.label}
                </Text>
              </Pressable>
            );
          })}
        </View>

        {!platform ? (
          <Text style={styles.muted}>{t("customBundle.choosePlatformFirst")}</Text>
        ) : (
          <>
            <Text style={styles.section}>{t("customBundle.pickItems")}</Text>
            <View style={styles.chipRow}>
              {tabs.map((row) => {
                const active = tab === row.id;
                return (
                  <Pressable
                    key={row.id}
                    style={[styles.chip, active && { backgroundColor: accent }]}
                    onPress={() => setTab(row.id)}
                  >
                    <Text
                      style={[styles.chipText, active && styles.chipTextActive]}
                    >
                      {row.label}
                    </Text>
                  </Pressable>
                );
              })}
            </View>
            <TextInput
              style={styles.search}
              placeholder={t("customBundle.searchPlaceholder")}
              value={query}
              onChangeText={setQuery}
              onSubmitEditing={loadProducts}
              returnKeyType="search"
            />
            <View style={[styles.selectionBar, { borderColor: accent }]}>
              <Text style={styles.selectionBarCount}>
                {t("customBundle.itemCount", {
                  count: selectionCount,
                  max: maxItems,
                })}
              </Text>
              <Pressable
                style={[styles.selectionBarBtn, { backgroundColor: accent }]}
                onPress={scrollToBundle}
                accessibilityRole="button"
                accessibilityLabel={t("customBundle.viewBundle")}
              >
                <Text style={styles.selectionBarBtnText}>
                  {t("customBundle.viewBundle")}
                </Text>
                <FontAwesome name="chevron-down" size={12} color="#111" />
              </Pressable>
            </View>
            {loading ? <LoadingBlock /> : null}
            {!loading && products.length === 0 ? (
              <Text style={styles.muted}>{t("customBundle.empty")}</Text>
            ) : null}
            {products.map((product) => {
              const inBundle = isInBundle(product);
              return (
                <View key={product.id} style={styles.productRow}>
                  {product.image_url ? (
                    <Image
                      source={{ uri: product.image_url }}
                      style={styles.thumb}
                    />
                  ) : (
                    <View style={[styles.thumb, styles.thumbEmpty]} />
                  )}
                  <View style={styles.productBody}>
                    <Text style={styles.productName} numberOfLines={2}>
                      {product.name}
                    </Text>
                    <Text style={styles.price}>
                      {Number(product.price ?? 0).toFixed(2)} EGP
                    </Text>
                  </View>
                  <Pressable
                    style={[
                      styles.cartIconBtn,
                      inBundle
                        ? styles.cartIconBtnRemove
                        : { backgroundColor: accent },
                      !inBundle && !product.in_stock && styles.addBtnDisabled,
                    ]}
                    disabled={!inBundle && !product.in_stock}
                    accessibilityLabel={
                      inBundle
                        ? t("customBundle.removeOne")
                        : t("customBundle.add")
                    }
                    onPress={() => {
                      if (inBundle) {
                        removeOneOfProduct(
                          product.id,
                          product.variation_id ?? null,
                        );
                        return;
                      }
                      void tryAddProduct(product);
                    }}
                  >
                    <FontAwesome
                      name={inBundle ? "minus" : "cart-plus"}
                      size={18}
                      color={inBundle ? "#333" : "#111"}
                    />
                  </Pressable>
                </View>
              );
            })}
          </>
        )}

        <View
          onLayout={(e) => {
            trayOffsetY.current = e.nativeEvent.layout.y;
          }}
        >
          <Text style={styles.section}>{t("customBundle.yourBundle")}</Text>
          <Text style={styles.muted}>
            {t("customBundle.itemCount", {
              count: selectionCount,
              max: maxItems,
            })}{" "}
            · {selectionTotal.toFixed(2)} EGP
          </Text>
          {selection.length === 0 ? (
            <Text style={styles.muted}>{t("customBundle.trayEmpty")}</Text>
          ) : (
            selection.map((row) => (
              <View key={row.key} style={styles.productRow}>
                <View style={styles.productBody}>
                  <Text style={styles.productName}>{row.name}</Text>
                  {row.variationName ? (
                    <Text style={styles.muted}>{row.variationName}</Text>
                  ) : null}
                  <Text style={styles.price}>
                    {(row.price * row.quantity).toFixed(2)} EGP
                  </Text>
                </View>
                <View style={styles.qtyRow}>
                  <Pressable
                    style={styles.qtyBtn}
                    onPress={() => changeQty(row.key, -1)}
                  >
                    <FontAwesome name="minus" size={14} color="#333" />
                  </Pressable>
                  <Text style={styles.qtyValue}>{row.quantity}</Text>
                  <Pressable
                    style={styles.qtyBtn}
                    onPress={() => changeQty(row.key, 1)}
                  >
                    <FontAwesome name="plus" size={14} color="#333" />
                  </Pressable>
                </View>
              </View>
            ))
          )}

          <PrimaryButton
            label={
              submitting
                ? t("common.loading")
                : t("customBundle.checkout")
            }
            disabled={submitting || selectionCount < minItems}
            onPress={() => void submitBundle()}
          />
        </View>
      </FormScrollView>

      <Modal visible={!!picker} transparent animationType="fade">
        <View style={styles.modalBackdrop}>
          <View style={styles.modalCard}>
            <Text style={styles.section}>{t("customBundle.chooseVariation")}</Text>
            <Text style={styles.productName}>{picker?.name}</Text>
            <FlatList
              data={picker?.options || []}
              keyExtractor={(item) => String(item.id)}
              renderItem={({ item }) => (
                <Pressable
                  style={styles.optionRow}
                  onPress={() => {
                    if (!picker) return;
                    addLine({
                      key: `v:${item.id}`,
                      productId: picker.productId,
                      variationId: item.id,
                      slug: picker.slug,
                      name: picker.name,
                      variationName: item.name,
                      price: item.price,
                      quantity: 1,
                      imageUrl: picker.imageUrl,
                    });
                    setPicker(null);
                  }}
                >
                  <Text style={styles.productName}>{item.name}</Text>
                  <Text style={styles.price}>{item.price.toFixed(2)} EGP</Text>
                </Pressable>
              )}
            />
            <PrimaryButton
              label={t("common.cancel")}
              onPress={() => setPicker(null)}
            />
          </View>
        </View>
      </Modal>
    </Screen>
  );
}

const styles = StyleSheet.create({
  badge: {
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  title: { fontSize: 22, fontWeight: "800", color: "#111", marginBottom: 8 },
  lead: { fontSize: 14, color: "#555", lineHeight: 20, marginBottom: 16 },
  section: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
    marginTop: 12,
    marginBottom: 8,
  },
  muted: { color: "#777", marginBottom: 10 },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 12 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#e8e8e8",
  },
  chipText: { fontWeight: "700", color: "#333" },
  chipTextActive: { color: "#111" },
  search: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#ccc",
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
    backgroundColor: "#fff",
  },
  selectionBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    marginBottom: 12,
    borderRadius: 10,
    borderWidth: 1,
    backgroundColor: "#fff",
  },
  selectionBarCount: { flex: 1, fontWeight: "700", color: "#222" },
  selectionBarBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  selectionBarBtnText: { fontWeight: "800", color: "#111" },
  productRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e8e8e8",
  },
  thumb: { width: 56, height: 56, borderRadius: 8, backgroundColor: "#eee" },
  thumbEmpty: { backgroundColor: "#ddd" },
  productBody: { flex: 1 },
  productName: { fontWeight: "700", color: "#222" },
  price: { color: "#444", marginTop: 2 },
  cartIconBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  cartIconBtnRemove: {
    backgroundColor: "#fff",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "#ccc",
  },
  addBtnDisabled: { opacity: 0.4 },
  qtyRow: { flexDirection: "row", alignItems: "center", gap: 8 },
  qtyBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: "#e8e8e8",
    alignItems: "center",
    justifyContent: "center",
  },
  qtyValue: { minWidth: 20, textAlign: "center", fontWeight: "700" },
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#F7F7F5",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    maxHeight: "70%",
  },
  optionRow: {
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "#e0e0e0",
  },
});

// storefront-qwik/src/routes/[lang]/custom-bundle/index.tsx
import { $, component$, useSignal, useTask$, useComputed$ } from "@builder.io/qwik";
import {
  Link,
  routeLoader$,
  useNavigate,
  type DocumentHead,
} from "@builder.io/qwik-city";
import { CartPlusIcon, MinusIcon } from "~/components/icons";
import { JsonLd } from "~/components/seo/json-ld";
import {
  ApiError,
  fetchCustomBundleMeta,
  fetchCustomBundleProducts,
  fetchProduct,
} from "~/lib/api";
import { addCartItems } from "~/lib/cart-actions";
import { useCart } from "~/lib/cart-context";
import { formatPrice } from "~/lib/format";
import { isSupportedLocale } from "~/lib/i18n/config";
import { tStatic, useI18n } from "~/lib/i18n/context";
import { localePath } from "~/lib/i18n/paths";
import { toastError, toastSuccess } from "~/lib/notify";
import { publicSeoLinks } from "~/lib/seo-hreflang";
import { withStorefrontThemeHead } from "~/lib/storefront-head";
import type { CartItem, CustomBundleMeta, ProductSummary } from "~/lib/types";
import { useLangParam, useSiteSettings } from "~/routes/[lang]/layout";

export interface BundleSelectionLine {
  key: string;
  productId: number;
  variationId: number;
  slug: string | null;
  name: string;
  variationName: string;
  price: number;
  quantity: number;
  imageUrl: string | null;
}

export const useCustomBundlePage = routeLoader$(async ({ params, redirect, resolveValue }) => {
  const locale = isSupportedLocale(params.lang) ? params.lang : "en";
  const settings = await resolveValue(useSiteSettings);
  if (!settings.custom_bundle?.enabled) {
    throw redirect(302, localePath(locale, "/"));
  }

  try {
    const { data } = await fetchCustomBundleMeta(locale);
    return {
      meta: data,
      unavailable: false as const,
    };
  } catch (e) {
    const status = e instanceof ApiError ? e.status : 0;
    if (status === 404) {
      throw redirect(302, localePath(locale, "/"));
    }
    return {
      meta: {
        enabled: true,
        min_items: settings.custom_bundle?.min_items ?? 2,
        max_items: settings.custom_bundle?.max_items ?? 15,
        platforms: [
          { id: "ps5", label: "PS5" },
          { id: "ps4", label: "PS4" },
        ],
        tabs: [{ id: "all", label: tStatic(locale, "customBundle.tabAll") }],
      } satisfies CustomBundleMeta,
      unavailable: true as const,
    };
  }
});

/** Physical Custom Bundle builder → cart → checkout. */
export default component$(() => {
  const page = useCustomBundlePage();
  const settings = useSiteSettings();
  const currency = settings.value.currency;
  const { locale } = useI18n();
  const cart = useCart();
  const nav = useNavigate();

  const platform = useSignal<string>("");
  const tab = useSignal<string>("all");
  const query = useSignal("");
  const categoryTabs = useSignal<Array<{ id: string; label: string }>>([
    { id: "all", label: tStatic(locale, "customBundle.tabAll") },
  ]);
  const products = useSignal<ProductSummary[]>([]);
  const loading = useSignal(false);
  const loadError = useSignal("");
  const selection = useSignal<BundleSelectionLine[]>([]);
  const pendingKey = useSignal<string | null>(null);
  const variationPicker = useSignal<{
    productId: number;
    name: string;
    slug: string | null;
    imageUrl: string | null;
    options: Array<{ id: number; name: string; price: number; in_stock: boolean }>;
  } | null>(null);
  const submitting = useSignal(false);

  const meta = page.value.meta;
  const minItems = meta.min_items || 2;
  const maxItems = meta.max_items || 15;

  const selectionCount = useComputed$(() =>
    selection.value.reduce((sum, line) => sum + line.quantity, 0),
  );
  const selectionTotal = useComputed$(() =>
    selection.value.reduce((sum, line) => sum + line.price * line.quantity, 0),
  );
  const canSubmit = useComputed$(() => {
    const n = selectionCount.value;
    return n >= minItems && n <= maxItems && !submitting.value;
  });

  const loadProducts$ = $(async () => {
    if (!platform.value) {
      products.value = [];
      return;
    }
    loading.value = true;
    loadError.value = "";
    try {
      const result = await fetchCustomBundleProducts(
        {
          platform: platform.value,
          tab: tab.value,
          q: query.value.trim() || undefined,
          per_page: 40,
        },
        locale,
      );
      products.value = result.data ?? [];
    } catch (e) {
      products.value = [];
      loadError.value =
        e instanceof ApiError
          ? e.message || tStatic(locale, "customBundle.loadFailed")
          : tStatic(locale, "customBundle.loadFailed");
    } finally {
      loading.value = false;
    }
  });

  useTask$(async ({ track }) => {
    track(() => platform.value);
    if (!platform.value) {
      categoryTabs.value = [{ id: "all", label: tStatic(locale, "customBundle.tabAll") }];
      tab.value = "all";
      products.value = [];
      return;
    }
    try {
      const { data } = await fetchCustomBundleMeta(locale, platform.value);
      const tabs = data.tabs?.length
        ? data.tabs
        : [{ id: "all", label: tStatic(locale, "customBundle.tabAll") }];
      categoryTabs.value = tabs;
      if (!tabs.some((t) => t.id === tab.value)) {
        tab.value = "all";
      }
    } catch {
      categoryTabs.value = [{ id: "all", label: tStatic(locale, "customBundle.tabAll") }];
      tab.value = "all";
    }
  });

  useTask$(async ({ track }) => {
    track(() => platform.value);
    track(() => tab.value);
    if (!platform.value) {
      products.value = [];
      return;
    }
    await loadProducts$();
  });

  const addLine$ = $(async (line: BundleSelectionLine) => {
    const count = selection.value.reduce((sum, row) => sum + row.quantity, 0);
    if (count >= maxItems) {
      await toastError(tStatic(locale, "customBundle.maxReached", { max: String(maxItems) }));
      return;
    }
    const existing = selection.value.find((row) => row.key === line.key);
    if (existing) {
      if (count + 1 > maxItems) {
        await toastError(tStatic(locale, "customBundle.maxReached", { max: String(maxItems) }));
        return;
      }
      selection.value = selection.value.map((row) =>
        row.key === line.key ? { ...row, quantity: row.quantity + 1 } : row,
      );
    } else {
      selection.value = [...selection.value, line];
    }
  });

  const tryAddProduct$ = $(async (product: ProductSummary) => {
    if (!product.variation_id || !product.in_stock) {
      return;
    }
    const key = `v:${product.variation_id}`;
    pendingKey.value = key;
    try {
      if (product.has_options) {
        const { data: detail } = await fetchProduct(String(product.id), locale);
        const options = (detail.variations ?? [])
          .filter((v) => v.in_stock)
          .map((v) => ({
            id: v.id,
            name: v.name,
            price: v.price,
            in_stock: v.in_stock,
          }));
        if (options.length === 0) {
          await toastError(tStatic(locale, "customBundle.unavailable"));
          return;
        }
        if (options.length === 1) {
          const only = options[0];
          await addLine$({
            key: `v:${only.id}`,
            productId: product.id,
            variationId: only.id,
            slug: product.slug,
            name: product.name,
            variationName: only.name,
            price: only.price,
            quantity: 1,
            imageUrl: product.image_url,
          });
          return;
        }
        variationPicker.value = {
          productId: product.id,
          name: product.name,
          slug: product.slug,
          imageUrl: product.image_url,
          options,
        };
        return;
      }

      await addLine$({
        key,
        productId: product.id,
        variationId: product.variation_id,
        slug: product.slug,
        name: product.name,
        variationName: product.variation_name || "",
        price: product.price,
        quantity: 1,
        imageUrl: product.image_url,
      });
    } catch (e) {
      await toastError(
        e instanceof Error ? e.message : tStatic(locale, "customBundle.loadFailed"),
      );
    } finally {
      pendingKey.value = null;
    }
  });

  const pickVariation$ = $(async (variationId: number) => {
    const picker = variationPicker.value;
    if (!picker) return;
    const option = picker.options.find((o) => o.id === variationId);
    if (!option) return;
    await addLine$({
      key: `v:${option.id}`,
      productId: picker.productId,
      variationId: option.id,
      slug: picker.slug,
      name: picker.name,
      variationName: option.name,
      price: option.price,
      quantity: 1,
      imageUrl: picker.imageUrl,
    });
    variationPicker.value = null;
  });

  const removeLine$ = $((key: string) => {
    selection.value = selection.value.filter((row) => row.key !== key);
  });

  /** Remove one unit of a catalog product from the bundle (any matching variation). */
  const removeOneOfProduct$ = $((productId: number, variationId: number | null) => {
    const preferredKey = variationId ? `v:${variationId}` : null;
    const match =
      (preferredKey
        ? selection.value.find((row) => row.key === preferredKey)
        : undefined) ||
      selection.value.find((row) => row.productId === productId);
    if (!match) return;
    if (match.quantity <= 1) {
      selection.value = selection.value.filter((row) => row.key !== match.key);
      return;
    }
    selection.value = selection.value.map((row) =>
      row.key === match.key ? { ...row, quantity: row.quantity - 1 } : row,
    );
  });

  const changeQty$ = $((key: string, delta: number) => {
    const next: BundleSelectionLine[] = [];
    let total = 0;
    for (const row of selection.value) {
      if (row.key !== key) {
        total += row.quantity;
        next.push(row);
        continue;
      }
      const qty = row.quantity + delta;
      if (qty <= 0) {
        continue;
      }
      if (delta > 0 && total + qty > maxItems) {
        continue;
      }
      total += qty;
      next.push({ ...row, quantity: qty });
    }
    selection.value = next;
  });

  const submit$ = $(async () => {
    const n = selection.value.reduce((sum, row) => sum + row.quantity, 0);
    if (n < minItems) {
      await toastError(tStatic(locale, "customBundle.minRequired", { min: String(minItems) }));
      return;
    }
    if (n > maxItems) {
      await toastError(tStatic(locale, "customBundle.maxReached", { max: String(maxItems) }));
      return;
    }

    submitting.value = true;
    try {
      const items: CartItem[] = selection.value.map((row) => ({
        productId: row.productId,
        variationId: row.variationId,
        slug: row.slug,
        name: row.name,
        variationName: row.variationName,
        price: row.price,
        quantity: row.quantity,
        imageUrl: row.imageUrl,
      }));
      await addCartItems(cart, items);
      await toastSuccess(tStatic(locale, "customBundle.addedToCart"));
      await nav(localePath(locale, "/checkout"));
    } catch (e) {
      await toastError(
        e instanceof Error ? e.message : tStatic(locale, "customBundle.submitFailed"),
      );
    } finally {
      submitting.value = false;
    }
  });

  const search$ = $(async () => {
    await loadProducts$();
  });

  const howToLd = {
    "@context": "https://schema.org",
    "@type": "HowTo",
    name: tStatic(locale, "customBundle.title"),
    description: tStatic(locale, "customBundle.lead"),
    step: [
      {
        "@type": "HowToStep",
        position: 1,
        name: tStatic(locale, "customBundle.step1Title"),
        text: tStatic(locale, "customBundle.step1Text"),
      },
      {
        "@type": "HowToStep",
        position: 2,
        name: tStatic(locale, "customBundle.step2Title"),
        text: tStatic(locale, "customBundle.step2Text", {
          min: String(minItems),
          max: String(maxItems),
        }),
      },
      {
        "@type": "HowToStep",
        position: 3,
        name: tStatic(locale, "customBundle.step3Title"),
        text: tStatic(locale, "customBundle.step3Text"),
      },
    ],
  };

  return (
    <article class="content-page custom-bundle-page">
      <nav class="content-breadcrumb" aria-label={tStatic(locale, "a11y.breadcrumb")}>
        <Link href={localePath(locale, "/")}>{tStatic(locale, "nav.home")}</Link>
        <span aria-hidden="true">›</span>
        <span>{tStatic(locale, "nav.customBundle")}</span>
      </nav>

      <p class="custom-bundle-badge">{tStatic(locale, "customBundle.badge")}</p>
      <h1 class="content-title">{tStatic(locale, "customBundle.title")}</h1>
      <p class="content-prose custom-bundle-lead">{tStatic(locale, "customBundle.lead")}</p>

      <ol class="custom-bundle-steps">
        <li>
          <strong>{tStatic(locale, "customBundle.step1Title")}</strong>
          <span>{tStatic(locale, "customBundle.step1Text")}</span>
        </li>
        <li>
          <strong>{tStatic(locale, "customBundle.step2Title")}</strong>
          <span>
            {tStatic(locale, "customBundle.step2Text", {
              min: String(minItems),
              max: String(maxItems),
            })}
          </span>
        </li>
        <li>
          <strong>{tStatic(locale, "customBundle.step3Title")}</strong>
          <span>{tStatic(locale, "customBundle.step3Text")}</span>
        </li>
      </ol>

      {page.value.unavailable ? (
        <p class="alert alert-warning" role="status">
          {tStatic(locale, "customBundle.loadFailed")}
        </p>
      ) : null}

      <div class="custom-bundle-layout">
        <div class="custom-bundle-builder">
          <section class="custom-bundle-section">
            <h2>{tStatic(locale, "customBundle.choosePlatform")}</h2>
            <div class="custom-bundle-platforms" role="group" aria-label={tStatic(locale, "customBundle.choosePlatform")}>
              {meta.platforms.map((p) => (
                <button
                  key={p.id}
                  type="button"
                  class={`custom-bundle-platform${platform.value === p.id ? " is-active" : ""}`}
                  aria-pressed={platform.value === p.id}
                  onClick$={() => {
                    platform.value = p.id;
                    tab.value = "all";
                  }}
                >
                  {p.label}
                </button>
              ))}
            </div>
          </section>

          <section class="custom-bundle-section">
            <h2>{tStatic(locale, "customBundle.pickItems")}</h2>
            {!platform.value ? (
              <p class="footer-muted">{tStatic(locale, "customBundle.choosePlatformFirst")}</p>
            ) : (
              <>
                <div class="custom-bundle-tabs" role="tablist">
                  {categoryTabs.value.map((t) => (
                    <button
                      key={t.id}
                      type="button"
                      role="tab"
                      class={`custom-bundle-tab${tab.value === t.id ? " is-active" : ""}`}
                      aria-selected={tab.value === t.id}
                      onClick$={() => {
                        tab.value = t.id;
                      }}
                    >
                      {t.label}
                    </button>
                  ))}
                </div>
                <form
                  class="custom-bundle-search"
                  preventdefault:submit
                  onSubmit$={search$}
                >
                  <label class="sr-only" for="custom-bundle-q">
                    {tStatic(locale, "customBundle.search")}
                  </label>
                  <input
                    id="custom-bundle-q"
                    type="search"
                    value={query.value}
                    placeholder={tStatic(locale, "customBundle.searchPlaceholder")}
                    onInput$={(e) => {
                      query.value = (e.target as HTMLInputElement).value;
                    }}
                  />
                  <button type="submit" class="btn btn-secondary">
                    {tStatic(locale, "customBundle.search")}
                  </button>
                </form>

                {loading.value ? (
                  <p class="footer-muted" role="status">
                    {tStatic(locale, "common.loading")}
                  </p>
                ) : null}
                {loadError.value ? (
                  <p class="alert alert-error" role="alert">
                    {loadError.value}
                  </p>
                ) : null}
                {!loading.value && !loadError.value && products.value.length === 0 ? (
                  <p class="footer-muted">{tStatic(locale, "customBundle.empty")}</p>
                ) : null}

                <ul class="custom-bundle-product-list">
                  {products.value.map((product) => {
                    const key = `v:${product.variation_id ?? product.id}`;
                    const busy = pendingKey.value === key;
                    const inBundle = selection.value.some(
                      (row) =>
                        row.productId === product.id ||
                        (product.variation_id != null &&
                          row.key === `v:${product.variation_id}`),
                    );
                    return (
                      <li key={product.id} class="custom-bundle-product">
                        <div class="custom-bundle-product__media">
                          {product.image_url ? (
                            <img src={product.image_url} alt="" width={64} height={64} loading="lazy" />
                          ) : (
                            <span class="custom-bundle-product__placeholder" aria-hidden="true" />
                          )}
                        </div>
                        <div class="custom-bundle-product__body">
                          <div class="custom-bundle-product__name">{product.name}</div>
                          {product.variation_name ? (
                            <div class="footer-muted">{product.variation_name}</div>
                          ) : null}
                          <div class="custom-bundle-product__price">
                            {formatPrice(product.price, currency, locale)}
                          </div>
                        </div>
                        <button
                          type="button"
                          class={`custom-bundle-cart-btn${inBundle ? " is-remove" : ""}`}
                          disabled={
                            busy ||
                            (!inBundle &&
                              (!product.in_stock || !product.variation_id))
                          }
                          aria-label={
                            inBundle
                              ? tStatic(locale, "customBundle.removeOne")
                              : tStatic(locale, "customBundle.add")
                          }
                          onClick$={() => {
                            if (inBundle) {
                              removeOneOfProduct$(
                                product.id,
                                product.variation_id ?? null,
                              );
                              return;
                            }
                            tryAddProduct$(product);
                          }}
                        >
                          {busy ? (
                            <span class="sr-only">{tStatic(locale, "common.loading")}</span>
                          ) : inBundle ? (
                            <MinusIcon size={22} />
                          ) : (
                            <CartPlusIcon size={22} />
                          )}
                        </button>
                      </li>
                    );
                  })}
                </ul>
              </>
            )}
          </section>
        </div>

        <aside class="custom-bundle-tray" aria-label={tStatic(locale, "customBundle.yourBundle")}>
          <h2>{tStatic(locale, "customBundle.yourBundle")}</h2>
          {selection.value.length === 0 ? (
            <p class="footer-muted">{tStatic(locale, "customBundle.trayEmpty")}</p>
          ) : (
            <ul class="custom-bundle-tray-list">
              {selection.value.map((line) => (
                <li key={line.key} class="custom-bundle-tray-item">
                  <div>
                    <div class="custom-bundle-tray-item__name">{line.name}</div>
                    {line.variationName ? (
                      <div class="footer-muted">{line.variationName}</div>
                    ) : null}
                    <div class="custom-bundle-tray-item__price">
                      {formatPrice(line.price * line.quantity, currency, locale)}
                    </div>
                  </div>
                  <div class="custom-bundle-tray-item__actions">
                    <button type="button" class="btn btn-secondary" onClick$={() => changeQty$(line.key, -1)}>
                      −
                    </button>
                    <span>{line.quantity}</span>
                    <button type="button" class="btn btn-secondary" onClick$={() => changeQty$(line.key, 1)}>
                      +
                    </button>
                    <button
                      type="button"
                      class="btn btn-danger"
                      onClick$={() => removeLine$(line.key)}
                    >
                      {tStatic(locale, "common.remove")}
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          )}

          <div class="custom-bundle-tray-summary">
            <div>
              {tStatic(locale, "customBundle.itemCount", {
                count: String(selectionCount.value),
                max: String(maxItems),
              })}
            </div>
            <div class="custom-bundle-tray-total">
              {formatPrice(selectionTotal.value, currency, locale)}
            </div>
          </div>

          <button
            type="button"
            class="btn btn-primary custom-bundle-submit"
            disabled={!canSubmit.value}
            onClick$={submit$}
          >
            {submitting.value
              ? tStatic(locale, "common.loading")
              : tStatic(locale, "customBundle.checkout")}
          </button>
          {selectionCount.value > 0 && selectionCount.value < minItems ? (
            <p class="footer-muted">
              {tStatic(locale, "customBundle.minRequired", { min: String(minItems) })}
            </p>
          ) : null}
        </aside>
      </div>

      {variationPicker.value ? (
        <div class="custom-bundle-modal" role="dialog" aria-modal="true">
          <div class="custom-bundle-modal__card">
            <h3>{tStatic(locale, "customBundle.chooseVariation")}</h3>
            <p class="footer-muted">{variationPicker.value.name}</p>
            <ul class="custom-bundle-variation-list">
              {variationPicker.value.options.map((opt) => (
                <li key={opt.id}>
                  <button
                    type="button"
                    class="btn btn-secondary"
                    onClick$={() => pickVariation$(opt.id)}
                  >
                    {opt.name} — {formatPrice(opt.price, currency, locale)}
                  </button>
                </li>
              ))}
            </ul>
            <button
              type="button"
              class="btn btn-secondary"
              onClick$={() => {
                variationPicker.value = null;
              }}
            >
              {tStatic(locale, "common.cancel")}
            </button>
          </div>
        </div>
      ) : null}

      <JsonLd data={howToLd} />
    </article>
  );
});

export const head: DocumentHead = ({ resolveValue, url }) => {
  const settings = resolveValue(useSiteSettings);
  const lang = resolveValue(useLangParam);
  const title = `${tStatic(lang, "customBundle.title")} — ${settings.business_name}`;
  const description = tStatic(lang, "customBundle.lead");

  return withStorefrontThemeHead(
    {
      title,
      meta: [
        { name: "description", content: description },
        { property: "og:title", content: title },
        { property: "og:description", content: description },
        { property: "og:type", content: "website" },
        { property: "og:url", content: url.href },
        { name: "twitter:card", content: "summary" },
        { name: "twitter:title", content: title },
        { name: "twitter:description", content: description },
      ],
      links: publicSeoLinks(url.origin, "/custom-bundle", lang),
    },
    settings,
  );
};
